Onyx structure types
blazejkustra/App pull request #1
Opened 2023-06-29 15:15 UTC by blazejkustra

2023-07-05 15:23 UTC, thiagobrez commented on src/ONYXKEYS.ts
> +    // [ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM]: OnyxTypes.Form; // TODO: REIMBURSEMENT_ACCOUNT_FORM has the same value as REIMBURSEMENT_ACCOUNT
Looks like it was a mistake when `REIMBURSEMENT_ACCOUNT_FORM` was added, that should have had value `reimbursementAccountForm` with "Form" at the end, following the pattern

From a quick project-wide search, looks safe to change. The question is if you want to do it in this PR

2023-07-05 15:29 UTC, thiagobrez commented on src/types/onyx/IOU.ts
> +};
Just curious: I noticed this type and others that I had investigated previously have a significant amount of keys that I wasn't able to spot in the initial investigation (which is excellent!). Do you think it just that these types evolved since last time, or you managed to find extra usages of these types that I did not see with my search method?

2023-07-05 15:45 UTC, thiagobrez commented on src/types/onyx/Paypal.ts
> +    pendingAction?: OnyxCommon.PendingAction;
`pendingAction`, `isLoading`, `errors` looks like a pattern at this point. I suspect that every type we consume even one of those, they probably have every key from `OnyxCommon.BaseState`. Of course, just by looking at the frontend it's impossible to know.

I also know the backend team won't be able to answer everything too, but maybe this one is worth asking?

2023-07-05 15:55 UTC, thiagobrez commented on src/types/onyx/Policy.ts
> +    errorFields?: Record<string, Record<string, string>>;
Shouldn't here use `number`?

```suggestion
    errorFields?: Record<number, Record<string, string>>;
```


Because on `withPolicy.js`, the example on this field says this:
```
        /**
         * Error objects keyed by field name containing errors keyed by microtime
         * E.x
         * {
         *     name: {
         *        [DateUtils.getMicroseconds()]: 'Sorry, there was an unexpected problem updating your workspace name.',
         *     }
         * }
         */
          errorFields: PropTypes.objectOf(PropTypes.objectOf(PropTypes.string)),

```

And `DateUtils.getMicroseconds()` returns a number

2023-07-05 15:55 UTC, thiagobrez commented on src/types/onyx/Policy.ts
> +    errorFields?: Record<string, Record<string, string>>;
Bookmark 🔖 , continuing from here tomorrow

2023-07-05 18:04 UTC, hayata-suenaga commented on src/types/onyx/Report.ts
> +    type?: string;
We have a set of report types. Instead of `string`, we can define a union type of literal strings for the `type` property. (ex. type: "taskReport", "iouReport"...)

_please not that example task report names I listed above is not exact. we need internal engineers' help or more investigation on the front end code ot figure out the list of report type names_

2023-07-05 18:42 UTC, neil-marcellini reviewed
Commenting so this shows in K2 and I remember to review later.

2023-07-05 18:46 UTC, hayata-suenaga commented
Requested internal engineers' review on [the core data PR](https://github.com/blazejkustra/App/pull/1) in NewDot [here (internal link)](https://expensify.slack.com/archives/C03TQ48KC/p1688582372669129).

2023-07-05 18:55 UTC, thienlnam commented
Same, adding myself to review

2023-07-06 00:18 UTC, puneetlath commented on src/types/onyx/PersonalDetails.ts
> +type PersonalDetails = {
This should also include the accountID which is a number.

2023-07-06 06:41 UTC, Beamanator commented on src/types/onyx/PersonalDetails.ts
> +type PersonalDetails = {
Yep - we also have `validated` and `phoneNumber` I'm seeing in Onyx at the moment

2023-07-06 09:14 UTC, thiagobrez commented on src/types/onyx/PolicyMember.ts
> +    pendingAction?: string;
Should we also use `OnyxCommon.PendingAction` here?

2023-07-06 13:34 UTC, blazejkustra commented on src/types/onyx/IOU.ts
> +};
Probably both! I checked other Onyx usages such as Onyx.update Onyx.connect etc, maybe that's why I found more values?

2023-07-06 13:54 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    pendingAction?: OnyxCommon.PendingAction;
Yes, you are probably right.

@hayata-suenaga do you know who to ask in this case? Could you link some backend engs that could answer?

2023-07-06 13:58 UTC, blazejkustra commented on src/types/onyx/Policy.ts
> +    errorFields?: Record<string, Record<string, string>>;
I noticed that in some places it was string in others it was number, so I just went with string as it also accepts numbers. However number may be more accurate here. Wdyt @fabioh8010 @hayata-suenaga?

From guidelines:
> Even though `string` is specified as a key, `Record<string, unknown>` type can still accepts objects whose keys are numbers. This is because numbers are converted to strings when used as an object index. Note that you cannot use [symbols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol) for `Record<string, unknown>`.

2023-07-06 14:03 UTC, blazejkustra commented on src/types/onyx/PersonalDetails.ts
> +type PersonalDetails = {
@Beamanator What are the types of `validated` and `phoneNumber` (probably boolean and string), are these fields required or optional?

2023-07-06 15:26 UTC, thiagobrez commented on src/types/onyx/IOU.ts
> +};
Cool! Maybe, I don't quite remember 🤔

2023-07-06 15:27 UTC, thiagobrez commented on src/types/onyx/Policy.ts
> +    errorFields?: Record<string, Record<string, string>>;
Makes sense to me 👍🏻

2023-07-06 17:16 UTC, grgia commented on src/types/onyx/ReportAction.ts
> +    whisperedToAccountIDs: number[];
For Threads, there's some optional reportAction keys:
here's an example of a thread:

```
  "4046468171698677818": {
    "person": [
      {
        "type": "TEXT",
        "style": "strong",
        "text": "New 2 Name 2"
      }
    ],
    "actorEmail": "hello@golden.com",
    "actorAccountID": 56,
    "message": [
      {
        "type": "COMMENT",
        "html": "test 3",
        "text": "test 3",
        "isEdited": false,
        "whisperedTo": [],
        "isDeletedParentAction": false,
        "reactions": []
      }
    ],
    "originalMessage": {
      "html": "test 3"
    },
    "avatar": "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/avatar_7.png",
    "created": "2023-04-18 13:12:54.112",
    "timestamp": 1681823574,
    "reportActionTimestamp": 1681823574112,
    "automatic": false,
    "actionName": "ADDCOMMENT",
    "shouldShow": true,
    "reportActionID": "4046468171698677818",
    "childReportID": 803008862104913,
    "childType": "chat",
    "childOldestFourEmails": "georgia@expensify.com",
    "childOldestFourAccountIDs": "3",
    "childCommenterCount": 1,
    "childLastVisibleActionCreated": "2023-05-10 10:09:43.680",
    "childVisibleActionCount": 1,
    "whisperedTo": [],
    "whisperedToAccountIDs": [],
    "lastModified": "2023-04-18 13:12:54.112"
  },
```

We're definitely at least missing:

``` ts
    childReportID?: number
    childType?:  string
    childOldestFourEmails?: string
    childOldestFourAccountIDs?: string
    childCommenterCount?: number,
    childLastVisibleActionCreated?: string
    childVisibleActionCount?: number
```

2023-07-06 17:19 UTC, grgia commented on src/types/onyx/Report.ts
> +    writeCapability?: ValueOf<typeof CONST.REPORT.WRITE_CAPABILITIES>;
again for threads here's an example of a thread report:

```
{
  "reportID": "4548022685863723",
  "reportName": "Chat Report",
  "type": "chat",
  "chatType": "",
  "ownerEmail": "__FAKE__",
  "ownerAccountID": 0,
  "policyID": "_FAKE_",
  "participants": [
    "georgia@expensify.com",
    "hello@golden.com"
  ],
  "participantAccountIDs": [
    3,
    56
  ],
  "isPinned": false,
  "lastReadTime": "2023-07-06 17:18:11.417",
  "lastReadSequenceNumber": 0,
  "lastVisibleActionCreated": "2023-05-13 08:57:19.351",
  "lastMessageText": "hiii",
  "lastActorEmail": "georgia@expensify.com",
  "lastActorAccountID": 3,
  "notificationPreference": "always",
  "welcomeMessage": "",
  "stateNum": 0,
  "statusNum": 0,
  "oldPolicyName": "",
  "isOwnPolicyExpenseChat": false,
  "lastMessageHtml": "hiii",
  "hasOutstandingIOU": false,
  "hasParentAccess": true,
  "parentReportID": 4444742227669619,
  "parentReportActionID": "6321995948616588385",
  "writeCapability": "all",
  "displayName": "hi",
  "iouReportAmount": 0,
  "lastVisibleActionLastModified": "2023-05-13 08:57:19.351",
  "isWaitingOnBankAccount": false,
  "managerID": 0,
  "isLoadingReportActions": false,
  "isLoadingMoreReportActions": false,
  "hasDraft": false,
  "pendingFields": {
    "createChat": null
  },
  "errorFields": {
    "createChat": null
  },
  "isOptimisticReport": false
}
```

and I think here we're at least missing:
```
  hasParentAccess?: boolean,
  parentReportID?: number,
  parentReportActionID?: string,

```

2023-07-06 17:34 UTC, thienlnam requested changes

2023-07-06 17:34 UTC, thienlnam commented on src/types/onyx/Task.ts
> +    title?: string;
title is always required

2023-07-06 17:34 UTC, thienlnam commented on src/types/onyx/Report.ts
> +};
There seem to be a few items missing from here displayName, hasDraft, welcomeMessage

Just going to paste this in if that helps
```
It appears that the provided text is not correctly formatted as a JSON object, so I'll do my best to create a JSON object based on the text you provided:

json
Copy code
{
  "chatType": "policyAdmins",
  "displayName": "#admins",
  "errorFields": {
    "createChat": null
  },
  "hasDraft": false,
  "hasOutstandingIOU": false,
  "iouReportAmount": 0,
  "isLoadingMoreReportActions": false,
  "isLoadingReportActions": false,
  "isOptimisticReport": false,
  "isOwnPolicyExpenseChat": false,
  "isPinned": false,
  "isWaitingOnBankAccount": false,
  "lastActorAccountID": 666702,
  "lastActorEmail": "jack@expensify.com",
  "lastMessageHtml": "added Jack Nam (jack.nam.1999@gmail.com) as a user",
  "lastMessageText": "added Jack Nam (jack.nam.1999@gmail.com) as a user",
  "lastReadSequenceNumber": 0,
  "lastReadTime": "2023-07-06 17:29:23.560",
  "lastVisibleActionCreated": "2023-07-03 21:57:20.283",
  "lastVisibleActionLastModified": "2023-07-03 21:57:20.283",
  "managerID": 0,
  "notificationPreference": "always",
  "oldPolicyName": "",
  "ownerAccountID": 0,
  "ownerEmail": "__fake__",
  "participantAccountIDs": [666702],
  "participants": ["jack@expensify.com"],
  "pendingFields": {
    "createChat": null
  },
  "policyID": "0FE374A21818A613",
  "reportID": "3514124523590689",
  "reportName": "#admins",
  "stateNum": 0,
  "statusNum": 0,
  "type": "chat",
  "welcomeMessage": "",
  "writeCapability": "all"
}
```

2023-07-06 19:12 UTC, luacmartins requested changes

2023-07-06 19:12 UTC, luacmartins commented on src/types/onyx/IOU.ts
> +    participants?: Participant[];
I think this key also has `loading` and `error`

2023-07-06 19:12 UTC, luacmartins commented on src/types/onyx/Paypal.ts
> +    pendingAction?: OnyxCommon.PendingAction;
I _think_ these keys are pretty common, but I can't say for sure that every Onyx key has them.

2023-07-06 19:12 UTC, luacmartins commented on src/types/onyx/PersonalBankAccount.ts
> +type PersonalBankAccount = {
Same comment as for BankAccount above. I suspect that we're missing a lot of keys here

2023-07-06 19:12 UTC, luacmartins commented on src/types/onyx/PlaidData.ts
> +type PlaidData = OnyxCommon.BaseState & {
same here

![Screenshot 2023-07-06 at 1 04 51 PM](https://github.com/blazejkustra/App/assets/22219519/d7032279-8a91-4a8f-8aab-454c66dc0683)

2023-07-06 19:12 UTC, luacmartins commented on src/types/onyx/Policy.ts
> +type Policy = {
I see a few more keys

![Screenshot 2023-07-06 at 1 06 20 PM](https://github.com/blazejkustra/App/assets/22219519/9d977883-35cf-43b6-b656-ada41208473c)

2023-07-06 19:12 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +        IOUTransactionID?: string;
IOU actions have a few more keys:

![Screenshot 2023-07-06 at 1 10 08 PM](https://github.com/blazejkustra/App/assets/22219519/038003ed-5d64-4044-a9e7-d3d6e920333e)

2023-07-06 19:12 UTC, luacmartins commented on src/types/onyx/Transaction.ts
> +    errors?: Record<string, string>;
We're missing `modifiedAmount`, `modifiedCreated` and `modifiedCurrency`

2023-07-06 19:40 UTC, neil-marcellini commented on src/types/onyx/OnyxCommon.ts
> +    errors?: Record<string, string>;
Let's add `errorFields` too, since that's an alternative error format for any key.

2023-07-06 19:40 UTC, neil-marcellini commented on src/types/onyx/BankAccount.ts
> +};
I expanded the type based on what we return from the backend [here](https://github.com/Expensify/Web-Expensify/blob/bacef866c1fba5bba56dd23d839838b6fd520fa9/lib/BankAccount.php#L655) (for internal reference). Maybe you can define some more strict types for some of these.

```ts
type BankAccount = {
    /** The name of the institution (bank of america, etc */
    addressName?: string;

    /** Alias for addressName*/
    title?: string;

    /** The masked bank account number */
    accountNumber?: string;

    /** The bankAccountID in the bankAccounts db */
    bankAccountID?: number;

    /** Alias for bankAccountID */
    methodID?: number,

    /** The bank account type */
    type?: string;

    isDefault?: boolean;

    /** string like 'Account ending in XXXX' */
    description?: string,

    /** string like 'bankAccount-{<bankAccountID>}' where <bankAccountID> is the bankAccountID*/
    key?: string,

    /** All data related to the bank account */
    accountData?: Record<string, unknown>,
};
```

Maybe we should return less data from our backend however, because I don't think we use most of this in App 🤔

2023-07-06 19:40 UTC, neil-marcellini commented on src/types/onyx/BankAccount.ts
> +};
🔖 I'm stopping here for now, I'll review more next time.

2023-07-07 14:38 UTC, blazejkustra commented on src/ONYXKEYS.ts
> +    // [ONYXKEYS.FORMS.REIMBURSEMENT_ACCOUNT_FORM]: OnyxTypes.Form; // TODO: REIMBURSEMENT_ACCOUNT_FORM has the same value as REIMBURSEMENT_ACCOUNT
I think it makes sense to remove it and use `REIMBURSEMENT_ACCOUNT` everywhere instead.

2023-07-07 14:50 UTC, blazejkustra commented on src/types/onyx/Report.ts
> +    writeCapability?: ValueOf<typeof CONST.REPORT.WRITE_CAPABILITIES>;
Thank you! From what I see in App code we were missing more than that:
```ts
    parentReportID?: number;
    parentReportActionID?: string;
    isOptimisticReport?: boolean;
    hasDraft?: boolean;
    managerID?: number;
    lastVisibleActionLastModified?: string;
    displayName?: string;
    lastMessageHtml?: string;
    welcomeMessage?: string;
    lastActorAccountID?: string;
    ownerAccountID?: number;
    participantAccountIDs?: number[];
```

2023-07-07 14:52 UTC, blazejkustra commented on src/types/onyx/BankAccount.ts
> +type BankAccount = {
@luacmartins Can you copy the text as it will be easier for me to copy paste and find occurances with my IDE 🙌

2023-07-07 14:53 UTC, blazejkustra commented on src/types/onyx/Card.ts
> +type Card = {
[Same](https://github.com/blazejkustra/App/pull/1#discussion_r1255950266) 🙏

2023-07-07 14:54 UTC, blazejkustra commented on src/types/onyx/IOU.ts
> +    participants?: Participant[];
I don't think it is used in the app, correct me if I'm wrong! 🤔

2023-07-07 14:55 UTC, blazejkustra commented on src/types/onyx/PlaidData.ts
> +type PlaidData = OnyxCommon.BaseState & {
[Same](https://github.com/blazejkustra/App/pull/1#discussion_r1255950266) 🙏

2023-07-07 14:55 UTC, blazejkustra commented on src/types/onyx/Policy.ts
> +type Policy = {
[Same](https://github.com/blazejkustra/App/pull/1#discussion_r1255950266) 🙏

2023-07-07 14:55 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +        IOUTransactionID?: string;
[Same](https://github.com/blazejkustra/App/pull/1#discussion_r1255950266) 🙏

2023-07-07 14:58 UTC, blazejkustra commented on src/types/onyx/BankAccount.ts
> +};
Thanks! 🙌

2023-07-07 14:59 UTC, blazejkustra commented on src/types/onyx/BankAccount.ts
> +type BankAccount = {
I added some types to BankAccount.

2023-07-07 15:01 UTC, blazejkustra commented on src/types/onyx/Task.ts
> +    shareDestination?: string;
Interesting, it is used in the app:
![image](https://github.com/blazejkustra/App/assets/46095609/8f1694a6-05c9-4416-b499-86db02790f05). Can you double check this one? @thienlnam

2023-07-07 16:55 UTC, thienlnam commented on src/types/onyx/Task.ts
> +    shareDestination?: string;
Damn, I guess it's used in the App but not actually stored in the report data - I guess it's fine to keep but might be confusing

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/ReimbursementAccount.ts
> +type AchData = {
I think our naming styleguide asks for uppercase shortcuts 
```suggestion
type ACHData = {
```

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/ReimbursementAccount.ts
> +    achData?: AchData;
```suggestion
    achData?: ACHData;
```

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/Paypal.ts
> +    pendingAction?: OnyxCommon.PendingAction;
I am not sure if pendingAction is a key for every Onyx key, it will be the case for any we can change using some optimistic api, but in case there is any key we just read/consume from the be it does not need to have pendingAction I think

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/PersonalDetails.ts
> +    /** login of the current user from their personal details */
```suggestion
    /** Login of the current user from their personal details */
```

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/PersonalDetails.ts
> +    /** pronouns of the current user from their personal details */
```suggestion
    /** Pronouns of the current user from their personal details */
```

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/PersonalDetails.ts
> +    /** local currency for the user */
```suggestion
    /** Local currency for the user */
```

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/PersonalDetails.ts
> +    /** timezone of the current user from their personal details */
```suggestion
    /** Timezone of the current user from their personal details */
```

2023-07-07 22:31 UTC, mountiny commented on src/types/onyx/PlaidBankAccount.ts
> +    /** last 4 digits of the account number */
```suggestion
    /** Last 4 digits of the account number */
```

2023-07-10 09:24 UTC, blazejkustra commented on src/types/onyx/BankAccount.ts
> +type BankAccount = {
cc @luacmartins

2023-07-10 19:16 UTC, neil-marcellini requested changes
I have reviewed OnyxCommon, Account, BankAccount, and Network and it's looking good. A few more keys to add for Account. Next time I'll pick up some more files if any are still unreviewed.

2023-07-10 19:16 UTC, neil-marcellini commented on src/types/onyx/Account.ts
Here are some extra keys I found stored for my account:
```
doesDomainHaveApprovedAccountant: false
hasEmailDeliveryFailure: false
hasSAMLLogin: false
```

2023-07-10 19:16 UTC, neil-marcellini commented on src/types/onyx/Account.ts
Searching the backend for uses of `OnyxKeys::ACCOUNT` I found these keys as well.
```ts
    /** Whether the account exists */
    accountExists?: boolean,

    /** Is the account / domain under domain control? */
    domainControlled?: boolean,

    /** Whether the validation code has expired */
    validateCodeExpired?: boolean,
```

2023-07-11 01:50 UTC, NikkiWines commented on src/types/onyx/Policy.ts
> +type Policy = {
From what I can see in our internal repos we return the following keys. Adding ✅  to the ones that are appropriately typed. 

- id ✅ 
- name ✅ 
- role ✅ 
- type ✅ 
- owner ✅ 
- outputCurrency ✅ 
- avatar ✅ 
- errorFields ✅ 
- isFromFullPolicy - bool|null ([internal link](https://github.com/Expensify/Web-Expensify/blob/54ece3a972205099dcf9069f3471dcdad7eea892/lib/AppInit.php#L76-L86))
- employeeList - array|null ([internal link](https://github.com/Expensify/Web-Expensify/blob/54ece3a972205099dcf9069f3471dcdad7eea892/lib/AppInit.php#L76-L86)
- errors - array|null ([internal link](https://github.com/Expensify/Web-Expensify/blob/54ece3a972205099dcf9069f3471dcdad7eea892/api.php#L761-L773))
- customUnits - array|null ([internal link](https://github.com/Expensify/Web-Expensify/blob/54ece3a972205099dcf9069f3471dcdad7eea892/lib/Policy/Utils.php#L990-L995))
- lastModified - string|null ([internal link](https://github.com/Expensify/Web-Expensify/blob/54ece3a972205099dcf9069f3471dcdad7eea892/lib/PolicyAPI.php#L3801))

@luacmartins I don't think we actually use a bunch of those keys from that screenshot above but can you confirm where we pass those to newDot?

2023-07-11 04:11 UTC, joelbettner approved these changes
I checked `ScreenShareRequest.ts` and it looks good. I've commented on the file in the PR with my evaluation.

2023-07-11 04:11 UTC, joelbettner commented on src/types/onyx/ScreenShareRequest.ts
> +type ScreenShareRequest = {
I did some digging. It looks like the `ScreenShareRequest.ts` file is good.

> Check if all properties listed are complete.

All of the properties are listed, as can be seen in their definition [here](https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/Expensify.js#L66-L73) and use [here](https://github.com/Expensify/App/blob/882026d659629d47cda410d120a00ac2a2cc0c61/src/Expensify.js#L198C36-L198C36).

> Question string types

All of the properties have a type of `string`, but that makes sense because an access token is an alphanumeric that is not predefined and the room name is also an alphanumeric that is not predefined.

> Are there any properties that are required?

All of the properties are required, as the access token is needed to get into any screen share room and a room name is needed for any screen share room.

2023-07-11 08:30 UTC, Beamanator commented on src/types/onyx/IOU.ts
FYI it looks like we don't update this from the backend, so everything you see on the frontend is what we have :D

2023-07-11 08:42 UTC, Beamanator commented on src/types/onyx/IOU.ts
> +    accountID?: number;
Do we want comments over all of these? I think so since we used to in propTypes?

2023-07-11 15:25 UTC, flodnv commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
Are we sure all fields in this type can be optional? Feels suspicious to me, especially for `idNumber`... I can help you answer this if you tell me: Where is this used in the App? What API call is returning this object?

2023-07-11 17:46 UTC, pecanoro commented on src/types/onyx/ReimbursementAccount.ts
> +    currentStep?: string;
According to our back-end, we have a limited set of steps: 
```
    public const STEP_BANK_ACCOUNT = 'BankAccountStep';
    public const STEP_COMPANY = 'CompanyStep';
    public const STEP_REQUESTOR = 'RequestorStep';
    public const STEP_ACH_CONTRACT = 'ACHContractStep';
    public const STEP_VALIDATION = 'ValidationStep';
    public const STEP_ENABLE = 'EnableStep';
```

2023-07-11 17:48 UTC, pecanoro commented on src/types/onyx/ReimbursementAccount.ts
> +    state?: string;
This is also a subset of states according to our back end:
```
    public const STATE_PENDING = 'PENDING';
    public const STATE_VALIDATION_FAILED = 'VALIDATION_FAILED';
    public const STATE_OPEN = 'OPEN';
    public const STATE_LOCKED = 'LOCKED';
    public const STATE_VERIFYING = 'VERIFYING';
    public const STATE_SETUP = 'SETUP';
```

2023-07-11 18:19 UTC, aldo-expensify requested changes

2023-07-11 18:19 UTC, aldo-expensify commented on src/types/onyx/Currency.ts
> +};
```suggestion
type Currency = {
    /** Symbol for the currency */
    symbol: string;

    /** Name of the currency */
    name: string;

    /** ISO4217 Code for the currency */
    ISO4217: string;

    /** Number of decimals the currency can have, if this is missing, we assume it has 2 decimals */
    decimals?: number;
};
```

Reviewing this as part of: https://github.com/Expensify/Expensify/issues/297946

Why are we specifying `symbol`, `name` and `ISO4217` as optional properties? I see that they are always there:

https://github.com/Expensify/App/blob/5f11116ab221b76d1bc43d1916c2630c00979470/tests/unit/currencyList.json

Also, the decimal property, which, as far as I know is being used, is missing,

2023-07-11 18:20 UTC, aldo-expensify commented on src/types/onyx/ReimbursementAccount.ts
> +    currentStep?: string;
Agreed, this should be some enum type

2023-07-11 19:12 UTC, neil-marcellini commented on src/types/onyx/Account.ts
@blazejkustra bumping this

2023-07-11 19:13 UTC, neil-marcellini requested changes
We still need to add some extra keys to Account.ts. OnyxCommon, Account, BankAccount, Network, and QueuedOnyxUpdates look good.

2023-07-11 19:13 UTC, neil-marcellini commented on src/types/onyx/QueuedOnyxUpdates.ts
👍

2023-07-11 19:50 UTC, danieldoglas commented on src/types/onyx/Credentials.ts
> +
we might be missing accountID here https://github.com/Expensify/App/blob/a28769ec378170ccbddf4bac6da1a99aa413f5d1/src/libs/actions/Session/index.js#L417-L422

2023-07-11 21:22 UTC, iwiznia requested changes
Reviewed the src/types/onyx/UserWallet.ts file only

2023-07-11 21:22 UTC, iwiznia commented on src/types/onyx/UserWallet.ts
> +type UserWallet = {
Also walletLimit: ?int

2023-07-11 21:22 UTC, iwiznia commented on src/types/onyx/UserWallet.ts
> +type UserWallet = {
Also walletLimitEnforcementPeriod: ?int

2023-07-11 21:22 UTC, iwiznia commented on src/types/onyx/UserWallet.ts
> +type UserWallet = {
Also: onfidoFixableErrors it's an optional array of strings

2023-07-11 21:22 UTC, iwiznia commented on src/types/onyx/UserWallet.ts
> +    walletLinkedAccountType?: string;
Why is this not restricting the value to those fixed values and instead allowing any string?

2023-07-11 21:22 UTC, iwiznia commented on src/types/onyx/UserWallet.ts
> +    errorCode?: string;
This needs to be restricted to the values ssnError, kbaNeeded or kycFailed

2023-07-12 12:17 UTC, blazejkustra commented on src/types/onyx/UserWallet.ts
> +type UserWallet = {
@iwiznia Are you sure `onfidoFixableErrors` is present in `UserWallet`? I thought it can be only available in `OnfidoWallet`.

I added the rest props, thanks!

2023-07-12 12:23 UTC, blazejkustra commented on src/types/onyx/UserWallet.ts
> +    walletLinkedAccountType?: string;
Adjusted, thanks!

2023-07-12 12:25 UTC, blazejkustra commented on src/types/onyx/UserWallet.ts
> +    currentBalance?: number;
Adjusted, thanks!

2023-07-12 12:25 UTC, blazejkustra commented on src/types/onyx/UserWallet.ts
> +    errorCode?: string;
Adjusted, thanks!

2023-07-12 12:25 UTC, blazejkustra commented on src/types/onyx/UserWallet.ts
> +    currentStep?: ValueOf<typeof CONST.WALLET.STEP>;
Adjusted, thanks!

2023-07-12 12:27 UTC, blazejkustra commented on src/types/onyx/Credentials.ts
> +
Adjusted, thank you 👌

2023-07-12 13:34 UTC, Julesssss commented on src/types/onyx/User.ts
> +    isSubscribedToNewsletter?: boolean;
We can be sure this is not-null.

2023-07-12 13:35 UTC, Julesssss commented on src/types/onyx/User.ts
> +    validated?: boolean;
This also doesn't need to be optional

2023-07-12 13:37 UTC, Julesssss commented on src/types/onyx/User.ts
> +    isFromPublicDomain?: boolean;
This also doesn't need to be optional

2023-07-12 13:40 UTC, blazejkustra commented on src/types/onyx/Account.ts
Added, thanks!

2023-07-12 13:48 UTC, blazejkustra commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
Thanks, every possible help is welcome! 🙌 

It is mainly used [in this file](https://github.com/blazejkustra/App/blob/782ad4c7237ab378d6a05ab4b1b978c1fc69a987/src/libs/actions/Wallet.js), every function that uses `ONYXKEYS.WALLET_ADDITIONAL_DETAILS` (`Onyx.merge` and `API.write`). Does that help? @flodnv

2023-07-12 13:49 UTC, blazejkustra commented on src/types/onyx/PlaidBankAccount.ts
> +    plaidAccountID: string;
I copied it from [these](https://github.com/blazejkustra/App/blob/782ad4c7237ab378d6a05ab4b1b978c1fc69a987/src/pages/ReimbursementAccount/plaidDataPropTypes.js) prop types. Should I change it to string | number? @stitesExpensify

2023-07-12 13:50 UTC, blazejkustra commented on src/types/onyx/PlaidBankAccount.ts
> +    routingNumber: string;
Same [question](https://github.com/blazejkustra/App/pull/1#discussion_r1261212186) @stitesExpensify

2023-07-12 14:23 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccount.ts
> +    currentStep?: string;
Thanks! Changed it 👌

2023-07-12 14:31 UTC, blazejkustra commented on src/types/onyx/Policy.ts
> +type Policy = {
@NikkiWines I don't have access to internal links that you provided, could you double check whether these fields are null vs undefined? This is a slight but important difference in JS/TS world 😅

2023-07-12 14:32 UTC, blazejkustra commented on src/types/onyx/Transaction.ts
> +    errors?: Record<string, string>;
@luacmartins What are the types for these?

2023-07-12 14:35 UTC, blazejkustra commented on src/types/onyx/User.ts
> +    isUsingExpensifyCard?: boolean;
Thanks, adjusted!

2023-07-12 15:03 UTC, Julesssss commented on src/types/onyx/WalletTransfer.ts
> +};
Unfortunately, I don't think any of these can be made non-optional. We're only using this Onyx object locally and I don't think any of the fields are initialized prior to the feature being used

2023-07-12 15:04 UTC, Julesssss commented on src/types/onyx/WalletTransfer.ts
> +    errors?: Record<string, string>;
I'm curious where Record is defined? I'm unable to find it in the PR...

2023-07-12 15:07 UTC, Julesssss commented on src/types/onyx/WalletTransfer.ts
> +    errors?: Record<string, string>;
For my reference, [here](https://github.com/Expensify/Expensify/issues/297980) is the internal issue

2023-07-12 16:35 UTC, youssef-lr commented on src/types/onyx/Session.ts
> +};
I think we're missing `autoAuthState` which is used [here](https://github.com/Expensify/App/blob/fc273032b4239c53aac534fba7bddc454522aa75/src/pages/ValidateLoginPage/index.website.js#L102) and is of type `string`.

2023-07-12 17:27 UTC, luacmartins requested changes

2023-07-12 17:27 UTC, luacmartins commented on src/types/onyx/OnfidoWallet.ts
> +type OnfidoWallet = {
This key is actually named `WalletOnfido` instead of `OnfidoWallet`. I think the name should match the key

2023-07-12 17:27 UTC, luacmartins commented on src/types/onyx/OnfidoWallet.ts
> +    applicantID?: string;
Required

```suggestion
    applicantID: string;
```

2023-07-12 17:27 UTC, luacmartins commented on src/types/onyx/OnfidoWallet.ts
> +    sdkToken?: string;
Required
```suggestion
    sdkToken: string;
```

2023-07-12 17:27 UTC, luacmartins commented on src/types/onyx/OnfidoWallet.ts
> +    loading?: boolean;
This should be isLoading

```suggestion
    /** Loading state to provide feedback when we are waiting for a request to finish */
    isLoading?: boolean;
```

2023-07-12 17:27 UTC, luacmartins commented on src/types/onyx/OnfidoWallet.ts
> +    error?: string;
This should be errors

```suggestion
    errors?: Record<string, string>;
```

2023-07-12 17:27 UTC, luacmartins commented on src/types/onyx/OnfidoWallet.ts
> +    hasAcceptedPrivacyPolicy?: boolean;
Missing key:
```
shouldShowFailedKYC?: boolean
```

2023-07-12 18:05 UTC, thienlnam requested changes

2023-07-12 18:05 UTC, thienlnam commented on src/types/onyx/WalletStatement.ts
> +
We also need statementPageURL

https://github.com/Expensify/App/blob/826e3a92ce93b2ff1a80da941cf01e4220cdd961/src/components/WalletStatementModal/WalletStatementModalPropTypes.js#L11-L12

2023-07-12 18:14 UTC, luacmartins requested changes

2023-07-12 18:14 UTC, luacmartins commented on src/types/onyx/IOU.ts
> +    selected?: boolean;
Missing key:
```
reportID?: string
```

2023-07-12 19:21 UTC, danieldoglas reviewed
Credentials.ts LGTM

2023-07-13 07:50 UTC, Beamanator commented on src/types/onyx/PersonalDetails.ts
> +type PersonalDetails = {
Sorry for the delay, I'm jumping back in to this now :D

2023-07-13 07:52 UTC, Beamanator commented on src/types/onyx/PersonalDetails.ts
> +    displayName?: string;
This is also required - AFAIK there's no case we should NOT have a user's display name

```suggestion
    displayName: string;
```

2023-07-13 07:53 UTC, blazejkustra commented on src/types/onyx/OnfidoWallet.ts
> +type OnfidoWallet = {
Agree! Changed 👌

2023-07-13 07:53 UTC, Beamanator commented on src/types/onyx/PersonalDetails.ts
> +    avatar?: string;
This should also be required

```suggestion
    avatar: string;
```

2023-07-13 07:55 UTC, blazejkustra commented on src/types/onyx/OnfidoWallet.ts
> +    error?: string;
Thank you, adjusted!

2023-07-13 07:56 UTC, blazejkustra commented on src/types/onyx/OnfidoWallet.ts
> +    hasAcceptedPrivacyPolicy?: boolean;
Thank you, adjusted!

2023-07-13 08:00 UTC, blazejkustra commented on src/types/onyx/WalletStatement.ts
> +
I believe it is just a coincidence of names. `WalletStatementModal` component takes `statementPageURL` as a prop which is unrelated to onyx key. Let me know if I'm wrong @thienlnam

2023-07-13 08:01 UTC, blazejkustra commented on src/types/onyx/IOU.ts
> +    id?: string;
Adjusted 👌

2023-07-13 08:01 UTC, blazejkustra commented on src/types/onyx/IOU.ts
> +    accountID?: number;
Adjusted 👌

2023-07-13 08:01 UTC, blazejkustra commented on src/types/onyx/IOU.ts
> +    selected?: boolean;
Adjusted 👌

2023-07-13 08:02 UTC, blazejkustra commented on src/types/onyx/PersonalDetails.ts
> +    displayName?: string;
Adjusted, thanks 👌

2023-07-13 08:02 UTC, blazejkustra commented on src/types/onyx/PersonalDetails.ts
> +    avatar?: string;
Adjusted, thanks 👌

2023-07-13 08:04 UTC, Beamanator reviewed
PersonalDetails LGTM 👍

2023-07-13 08:15 UTC, blazejkustra commented on src/types/onyx/IOU.ts
> +    participants?: Participant[];
Yes, that's probably what we need to do while migrating `src/setup/index.js`.

2023-07-13 08:16 UTC, blazejkustra commented on src/types/onyx/Session.ts
> +};
Added, thanks! 😄

2023-07-13 12:51 UTC, flodnv commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
Ah I see... would it make sense / would it work to have `idNumber` non optional?

2023-07-13 16:43 UTC, mountiny reviewed
Checked the `Download.ts` and I believe its correct

2023-07-13 21:01 UTC, stitesExpensify commented on src/types/onyx/PlaidBankAccount.ts
> +    plaidAccountID: string;
If it is already a string and we aren't getting errors on those props then it should be fine.

2023-07-13 21:01 UTC, stitesExpensify commented on src/types/onyx/PlaidBankAccount.ts
> +    routingNumber: string;
Same as above, we're probably good here.

2023-07-13 21:02 UTC, amyevans commented on src/types/onyx/BlockedFromConcierge.ts
> +};
`expiresAt` doesn't need to be optional

Also this is missing `count: int`

2023-07-13 21:02 UTC, stitesExpensify commented
src/types/onyx/PlaidBankAccount.ts is good.

2023-07-13 21:09 UTC, amyevans reviewed
Reviewed `src/types/onyx/BlockedFromConcierge.ts`

2023-07-14 00:35 UTC, francoisl commented on src/ONYXKEYS.ts
> +    // Forms
[`REIMBURSEMENT_ACCOUNT_FORM`](https://github.com/Expensify/App/blob/a5f64675aa95f149b77077bf1f1bc474df1ce64a/src/ONYXKEYS.js#L196) was removed from `OnyxKeys.FORMS` [above](https://github.com/blazejkustra/App/pull/1/files#diff-facfc70b32eba19ccaeeadd16b51faf6dbf2ceb919373565e7322c86047886cdR220-R239), but shouldn't there be an entry for that form below with type description?

2023-07-14 02:19 UTC, roryabraham commented on src/types/onyx/Login.ts
> +    errorFields?: OnyxCommon.ErrorFields;
This looks correct, but it would be nice it we could get more specific about the possible keys here. For example, the only possible key in `pendingFields` and `errorFields` (AFAICT) is `addedLogin`. It would be awesome if we could capture that at compile time.

2023-07-14 08:56 UTC, techievivek reviewed
`WalletTerms.ts` LGTM.

2023-07-14 08:57 UTC, madmax330 reviewed
Reviewed Paypal.ts type

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    username?: string;
```suggestion
    username: string;
```

I think this should be required since it is the only param in the object.

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    title?: string;
```suggestion
    title: string;
```

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    description?: string;
```suggestion
    description: string;
```

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    methodID?: typeof CONST.PAYMENT_METHODS.PAYPAL;
```suggestion
    methodID: typeof CONST.PAYMENT_METHODS.PAYPAL;
```

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    accountType?: typeof CONST.PAYMENT_METHODS.PAYPAL;
```suggestion
    accountType: typeof CONST.PAYMENT_METHODS.PAYPAL;
```

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    key?: string;
```suggestion
    key: string;
```

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    isDefault?: boolean;
```suggestion
    isDefault: boolean;
```

2023-07-14 08:57 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    accountData?: PaypalAccountData;
```suggestion
    accountData: PaypalAccountData;
```

Looks like this is set here: https://github.com/Expensify/App/blob/405fcdf8850a62f6c02f96e34d71004144239a19/src/libs/actions/User.js#L507

2023-07-14 09:07 UTC, techievivek commented on src/types/onyx/WalletTerms.ts
> +    chatReportID?: string;
This is being passed in the method
```js
BankAccounts.acceptWalletTerms({
     hasAcceptedTerms: hasAcceptedDisclosure && hasAcceptedPrivacyPolicyAndWalletAgreement,
     chatReportID: props.walletTerms.chatReportID,
});
```

So if the `chatReportID` is empty wouldn't it be passed as `undefined`? So should we make it default to an empty string?

2023-07-14 22:11 UTC, yuwenmemon approved these changes

2023-07-14 22:13 UTC, yuwenmemon commented
Reviewed `src/types/onyx/SecurityGroup.ts` :+1:

2023-07-15 00:07 UTC, iwiznia commented on src/types/onyx/UserWallet.ts
> +type UserWallet = {
hmmmm good question.  am not quite sure, I suspect you are right, but let's ask @nkuoch

2023-07-15 07:05 UTC, nkuoch commented on src/types/onyx/UserWallet.ts
> +type UserWallet = {
From Web-Expensify I only see it being set in walletOnfido > fixableErrors

cc @MariaHCD

2023-07-16 14:36 UTC, MariaHCD commented
`Modal.ts` looks good to me!

2023-07-17 10:17 UTC, flodnv commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
@blazejkustra ?

2023-07-17 10:30 UTC, blazejkustra commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
Good question, I saw that `idNumber` has a default value [here](https://github.com/blazejkustra/App/blob/57ed3179b1f919076cbde086cfb03a160579bb5c/src/pages/EnablePayments/AdditionalDetailsStep.js), so I assumed it may be optional. Could you check if it's required on the backend? @flodnv

2023-07-17 10:40 UTC, blazejkustra commented on src/ONYXKEYS.ts
> +    // Forms
[Here](https://github.com/blazejkustra/App/pull/1#discussion_r1253244636) is a discussion that explains this change @francoisl

2023-07-17 10:50 UTC, blazejkustra commented on src/types/onyx/Login.ts
> +    errorFields?: OnyxCommon.ErrorFields;
Without real validation of data that comes from API I would be a little more careful with being more specific @roryabraham.

> I think we can slowly improve these types while migrating to TS, something to consider is to utilise some schema validation lib like [Zod](https://zod.dev/). With this we could validate every prop & set default values easier & be much more safe in runtime.

^ [link](https://swmansion.slack.com/archives/C0593T50UHG/p1689169004094369?thread_ts=1689168494.274249&cid=C0593T50UHG)

2023-07-17 10:50 UTC, blazejkustra commented on src/types/onyx/FrequentlyUsedEmoji.ts
> +    /** The timestamp of when the emoji was last used */
Adjusted, thanks!

2023-07-17 10:53 UTC, blazejkustra commented on src/types/onyx/FrequentlyUsedEmoji.ts
> +    lastUpdatedAt: number;
Adjusted, thanks!

2023-07-17 10:55 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    username?: string;
Have you checked it with the backend that it is indeed required? @madmax330

2023-07-17 10:55 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    title?: string;
Adjusted, thanks 👌

2023-07-17 10:56 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    description?: string;
Adjusted, thanks 👌

2023-07-17 10:56 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    isDefault?: boolean;
Adjusted, thanks 👌

2023-07-17 10:56 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    key?: string;
Adjusted, thanks 👌

2023-07-17 10:57 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    accountType?: typeof CONST.PAYMENT_METHODS.PAYPAL;
Adjusted, thanks 👌

2023-07-17 10:57 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    methodID?: typeof CONST.PAYMENT_METHODS.PAYPAL;
Adjusted, thanks 👌

2023-07-17 11:23 UTC, MariaHCD commented on src/types/onyx/UserWallet.ts
> +type UserWallet = {
Fixable errors is only set in the `walletOnfido` Onyx key in the backend [here](https://github.com/Expensify/Web-Expensify/blob/23bf05f4fc85e817bf42794ab504b1ba71396a91/lib/Error/Onfido/IdentityVerificationError.php#L45-L58).

2023-07-17 11:26 UTC, Julesssss commented on src/types/onyx/WalletTransfer.ts
> +    errors?: Record<string, string>;
Oh perfect, thanks

2023-07-17 11:31 UTC, blazejkustra commented on src/types/onyx/WalletTerms.ts
> +    chatReportID?: string;
If it's optional it makes sense to add a default value, but I wouldn't do it in this PR.

2023-07-17 11:33 UTC, Julesssss commented
`User` and `WalletTransfer` ✅

2023-07-17 11:46 UTC, flodnv commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
Honestly I'm unsure. Do you know @madmax330 @MariaHCD @nkuoch ?

2023-07-17 11:47 UTC, blazejkustra commented
Hey guys 👋 

I created a checklist (in the description of this PR) with all types. In order to better track what types are still in review! 😄 I’m constantly updating the types based on your feedback!

- `src/types/onyx/Card.ts`: @luacmartins
- `src/types/onyx/Credentials.ts`: @danieldoglas
- `src/types/onyx/FrequentlyUsedEmoji.ts`: @MonilBhavsar
- `src/types/onyx/IOU.ts`: @luacmartins
- `src/types/onyx/Paypal.ts`: @luacmartins / @madmax330
- `src/types/onyx/PersonalBankAccount.ts`: @luacmartins
- `src/types/onyx/PlaidData.ts`: @luacmartins
- `src/types/onyx/ReimbursementAccount.ts`: @pecanoro / @aldo-expensify 
- `src/types/onyx/ScreenShareRequest.ts`: @joelbettner
- `src/types/onyx/Session.ts`: @youssef-lr 
- `src/types/onyx/Task.ts`: @thienlnam
- `src/types/onyx/Transaction.ts`: @luacmartins
- `src/types/onyx/UserWallet.ts`: @iwiznia

Could you confirm that this file is aligned with the backend? ☝️

2023-07-17 11:50 UTC, blazejkustra commented
These files are awaiting review:

- `src/types/onyx/Beta.ts` 
- `src/types/onyx/Form.ts` 
- `src/types/onyx/Login.ts` 
- `src/types/onyx/OnfidoWallet.ts` 
- `src/types/onyx/PolicyMember.ts` 
- `src/types/onyx/PrivatePersonalDetails.ts` 
- `src/types/onyx/ReimbursementAccountDraft.ts` 
- `src/types/onyx/ReportActionFragment.ts` 
- `src/types/onyx/Request.ts` 
- `src/types/onyx/WalletAdditionalDetails.ts` 
- `src/types/onyx/WalletStatement.ts` 
- `src/types/onyx/WalletTerms.ts` 

@hayata-suenaga could you ask internals to look at these? ☝️ Thank you!

2023-07-17 12:16 UTC, MariaHCD commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
We don't always return the `idNumber` from the backend, we only return it during the [Knowledge Based Authentication (KBA) flow](https://github.com/Expensify/Web-Expensify/blob/23bf05f4fc85e817bf42794ab504b1ba71396a91/lib/Error/WalletAdditionalDetails/VerificationError.php#L71-L84) (when we need to ask the user some additional questions to verify their identity)

We send different data based on [different scenarios/errors](https://github.com/Expensify/Web-Expensify/blob/23bf05f4fc85e817bf42794ab504b1ba71396a91/lib/Error/WalletAdditionalDetails/VerificationError.php#L58-L130) at the Additional Details step of Wallet KYC, so I think it makes sense that the fields for this Onyx key are optional

2023-07-17 12:16 UTC, MariaHCD commented on src/types/onyx/WalletAdditionalDetails.ts
> +    /** Questions returned by Ideology */
```suggestion
    /** Questions returned by Idology */
```

2023-07-17 14:37 UTC, blazejkustra commented on src/types/onyx/WalletAdditionalDetails.ts
> +    /** Questions returned by Ideology */
Sorry for that, I didn't know what Idology was before 😅 Adjusted, thanks!

2023-07-17 15:31 UTC, amyevans commented on src/types/onyx/BlockedFromConcierge.ts
> +};
@blazejkustra The count is the number of times the user has been blocked. On the first offense, they're blocked for 1 day (and count set to 1). On the second offense, they're blocked for 1 week (and count set to 2). On the third offense (OR if the concierge agent deems they should be blocked permanently right away), they're blocked until 2999-12-31 (and count set to 3).

2023-07-17 16:24 UTC, luacmartins commented on src/types/onyx/BankAccount.ts
> +type BankAccount = {
Sure, here's the text form:

```
7: {
    accountData: {
      accountNumber: "111122XXXXXX1111",
      additionalData: {
        acceptTerms: true,
        addressCity: "1adsf",
        addressState: "AK",
        addressStreet: "123",
        addressZipCode: "12345",
        approvedBy: "Automatic",
        bankName: "",
        beneficialOwners: [],
        companyName: "Alberta Bobbeth Charleson",
        companyPhone: "2678257555",
        companyTaxID: "123456789",
        country: "US",
        currency: "USD",
        currentStep: "ACHContractStep",
        dateSigned: "2023-05-11 17:27:09",
        dob: "1990-01-01",
        enableCardAfterVerified: true,
        fieldsType: "local",
        firstName: "Alberta",
        hasFullSSN: true,
        hasNoConnectionToCannabis: true,
        incorporationDate: "1990-01-01",
        incorporationState: "SC",
        incorporationType: "CORPORATION",
        industryCode: "621111",
        isControllingOfficer: true,
        isOnfidoSetupComplete: true,
        lastName: "Charleson",
        lastUpdate: "2023-05-11 17:27:09",
        onfidoData: {
          applicantID: "generatedViaMarkedAsVerified",
        },
        ownsMoreThan25Percent: false,
        plaidAccountID: "",
        previousState: 2,
        requestorAddressCity: "adsfadfs",
        requestorAddressState: "SC",
        requestorAddressStreet: "1234",
        requestorAddressZipCode: "12345",
        setupType: "manual",
        ssnLast4: "1234",
        useOnfido: true,
        verifications: [],
        website: "https://www.expensifail.com",
      },
      addressName: "Alberta Bobbeth Charleson",
      allowDebit: true,
      bankAccountID: 7,
      created: "2023-04-25 09:14:25",
      defaultCredit: false,
      expensifyCardDomain: "ba.com",
      isExpensifyCardSettlementAccount: true,
      isSavings: false,
      processor: "bancorp",
      riskChecked: true,
      routingNumber: "011401533",
      sharees: ["ba@ba.com", "ba2@ba.com"],
      state: "OPEN",
      type: "BUSINESS",
    },
    accountType: "bankAccount",
    description: "Account ending in 1111",
    isDefault: false,
    key: "bankAccount-7",
    methodID: 7,
    title: "Alberta Bobbeth Charleson",
  }
```

2023-07-17 16:32 UTC, luacmartins commented on src/types/onyx/Card.ts
> +type Card = {
Here you go:

```
{
  3: {
    accountData: {
      additionalData: {
        isBillingCard: true,
        isP2PDebitCard: false,
      },
      addressName: "Test",
      addressState: "US",
      addressStreet: "",
      addressZip: 12345,
      cardMonth: 10,
      cardNumber: "424242XXXXXX4242",
      cardYear: 2030,
      created: "2023-07-17 16:27:49",
      currency: "USD",
      fundID: 3,
    },
    accountType: "debitCard",
    description: "Card ending in 4242",
    key: "card-3",
    methodID: 3,
    title: "Test",
  },
}
```

2023-07-17 16:50 UTC, luacmartins commented on src/types/onyx/PlaidData.ts
> +type PlaidData = OnyxCommon.BaseState & {
{
  bankAccounts: [{
    0: {
      accountNumber: "1111222233331111",
      addressName: "Plaid Saving",
      isSavings: true,
      mask: "1111",
      ownershipType: "",
      plaidAccountID: "DFSdksdfsafsdSFASDASD",
      routingNumber: "011401533",
    }
  }],
  bankName: "Citibank Online",
  error: "",
  isLoading: false,
  plaidAccessToken: "access-sandbox-12341234",
}

2023-07-17 16:56 UTC, luacmartins commented on src/types/onyx/Policy.ts
> +type Policy = {
I think you're correct @NikkiWines, we don't seem to use the majority of those keys. For now, I think we can go with [these fields](https://github.com/blazejkustra/App/pull/1#discussion_r1259085338)

2023-07-17 17:02 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +        IOUTransactionID?: string;
```
5249912074239480463: {
  actionName: "IOU",
  actorAccountID: 188,
  automatic: false,
  avatar: "https://d2k5nsl2zxldvw.cloudfront.net/images/avatars/default-avatar_22.png",
  childReportID: 2201626852502415,
  childType: "chat",
  created: "2023-06-20 22:32:10.045",
  lastModified: "2023-06-20 22:32:10.045",
  message: [{
    type: 'COMMENT',
    html: 'requested CA$1.00',
    text: 'requested CA$1.00',
    isEdited: false,
    whisperedTo: [],
  }],
  originalMessage: {
    IOUReportID: 8649835496605987,
    IOUTransactionID: "3433517791539032170",
    amount: 100,
    comment: "",
    currency: "CAD",
    lastModified: "2023-06-20 22:32:10.045",
    participantAccountIDs: [2, 188],
    participants: ['cmartins@expensifail.com', 'n2@n2.com'],
    type: "create",
  }
  person: [{type: 'TEXT', style: 'strong', text: 'n2@n2.com'}],
  reportActionID: "5249912074239480463",
  reportActionTimestamp: 1687300330045,
  shouldShow: true,
  timestamp: 1687300330,
  whisperedToAccountIDs: [],
} 
```

2023-07-17 17:45 UTC, roryabraham commented on src/types/onyx/Login.ts
> +    errorFields?: OnyxCommon.ErrorFields;
> Without real validation of data that comes from API I would be a little more careful with being more specific

I mean, I manually validated this (and that's kind of the point of this whole exercise). And by being more specific we might catch more errors if someone makes a breaking change in the API. Can we automate that process in the future? Probably. Would that be valuable? Yes, forsure – we have definitely talked a lot about automating compatibility between the API and the front-end via TypeScript.

Anyways, I think it's more important to get this merged and iterate from there, so 👍🏼 from me for now.

2023-07-17 17:57 UTC, luacmartins commented on src/types/onyx/Transaction.ts
> +    created?: string;
These are all required

2023-07-17 18:37 UTC, francoisl reviewed
`Form.ts` reviewed 👍

2023-07-17 21:09 UTC, neil-marcellini commented
@blazejkustra I think these are the only files that haven't been reviewed yet. All of them are assigned to internal engineers to review. I'll jump in and review PolicyMember and maybe ReportActionFragment to help move this forward.

- [ ] https://github.com/Expensify/Expensify/issues/297968
- [ ]  https://github.com/Expensify/Expensify/issues/297969
- [ ]  https://github.com/Expensify/Expensify/issues/297966
- [ ]  https://github.com/Expensify/Expensify/issues/297962
- [ ]  https://github.com/Expensify/Expensify/issues/297963

2023-07-17 21:48 UTC, cead22 commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    /** Props needed for CompanyStep */
Looks like we might be missing `bankName` or `bank` here
- [Here](https://github.com/Expensify/App/blob/d0cc4997c9/src/pages/ReimbursementAccount/CompanyStep.js#L143) we pull `bankName` from `this.props.reimbursementAccountDraft`
- We pass that to `BankAccounts.updateCompanyInformationForBankAccount`, which calls `UpdateCompanyInformationForBankAccount`
- In [api.php](https://github.com/Expensify/Web-Expensify/blob/c610bc4f435/api.php#L3065) it looks like we accept `bank` and not `bankName`

2023-07-17 21:54 UTC, neil-marcellini requested changes

2023-07-17 21:54 UTC, neil-marcellini commented on src/types/onyx/Account.ts
> +type Account = OnyxCommon.BaseState & {
I like how the Account type is an intersection with the BaseState. Can we do this for all the types? Maybe I missed this conversation, but why would we use the BaseState for some types and not all?

2023-07-17 21:54 UTC, neil-marcellini commented on src/types/onyx/PolicyMember.ts
> +    pendingAction?: OnyxCommon.PendingAction;
These can come from the BaseState

2023-07-17 21:54 UTC, neil-marcellini commented on src/types/onyx/PolicyMember.ts
> +type PolicyMember = {
I think we should intersect this with the BaseState.

2023-07-17 21:54 UTC, neil-marcellini commented on src/types/onyx/PolicyMember.ts
I checked the front and back end and it looks good.

2023-07-17 21:54 UTC, neil-marcellini commented on src/types/onyx/ReportActionFragment.ts
> +    isEdited: boolean;
I think these should all be optional. I'm also not seeing how we use many of these, but it probably doesn't hurt to keep them.

2023-07-17 21:58 UTC, pecanoro requested changes

2023-07-17 21:58 UTC, pecanoro commented on src/types/onyx/ReimbursementAccount.ts
> +    currentStep?: ValueOf<typeof CONST.BANK_ACCOUNT.STEP>;
When ACHData is defined, currentStep is always set.

2023-07-17 21:58 UTC, pecanoro commented on src/types/onyx/ReimbursementAccount.ts
> +type ACHData = {
It seems we can also have an optional property in ACHData called subStep:

![image](https://github.com/blazejkustra/App/assets/6474442/9aed628b-d929-475b-a138-69977c432edf)

2023-07-17 22:16 UTC, cead22 commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    certifyTrueInformation?: boolean;
I believe these four are only pulled from this.reimbursementAccount and not from this.reimbursementAccountDraft, so I think maybe we can get rid of these, but I'm not sure

2023-07-17 22:21 UTC, cead22 commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    isOnfidoSetupComplete?: boolean;
I believe all of these are also pulled from reimbursementAccount and not from reimbursementAccountDraft

2023-07-18 08:29 UTC, Beamanator reviewed
PrivatePersonalDetails looks good, just 1 question 👍

2023-07-18 08:29 UTC, Beamanator commented on src/types/onyx/PrivatePersonalDetails.ts
> +        country?: string;
Just checking here - `address` can be optional, BUT if it exists, these fields all are required... So do we have to keep these optional?

2023-07-18 11:35 UTC, blazejkustra commented on src/types/onyx/PlaidData.ts
> +type PlaidData = OnyxCommon.BaseState & {
I think that the type looks good already! Thanks!

2023-07-18 11:55 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +        IOUTransactionID?: string;
Thanks! I changed it quite a lot, have a look please! 🙌

2023-07-18 11:56 UTC, blazejkustra commented on src/types/onyx/Transaction.ts
> +    errors?: Record<string, string>;
Thank you, adjusted!

2023-07-18 12:41 UTC, blazejkustra commented on src/types/onyx/Card.ts
> +type Card = {
Adjusted, thanks!

2023-07-18 12:42 UTC, blazejkustra commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
Thanks! I'll leave it as is 👌

2023-07-18 12:44 UTC, blazejkustra commented on src/types/onyx/BlockedFromConcierge.ts
> +};
Thanks, adjusted!

2023-07-18 12:46 UTC, blazejkustra commented on src/types/onyx/Login.ts
> +    errorFields?: OnyxCommon.ErrorFields;
Agree! Let's iterate in the future 👌

2023-07-18 12:51 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    /** Props needed for CompanyStep */
I think backend should be our source of truth here, adding a `bank?: string` attribute. Thanks!

2023-07-18 14:04 UTC, blazejkustra commented on src/types/onyx/ReportActionFragment.ts
> +    isEdited: boolean;
I removed this file, I think the prop type was wrong. I adjusted ReportAction according to what @luacmartins wrote [here](https://github.com/blazejkustra/App/pull/1#discussion_r1254821676).

2023-07-18 14:06 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccount.ts
> +type ACHData = {
Nice find, adjusted!

2023-07-18 14:07 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    certifyTrueInformation?: boolean;
I think that if these are present on the backend it's okay to have it here even if these aren't used.

2023-07-18 14:10 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    certifyTrueInformation?: boolean;
Can someone double check it? Is the source of `reimbursementAccountDraft` defined on the backend? @cead22

2023-07-18 14:11 UTC, blazejkustra commented on src/types/onyx/PrivatePersonalDetails.ts
> +        country?: string;
No, we can make them required, adjusted 👌 Thanks!

2023-07-18 14:13 UTC, blazejkustra commented on src/types/onyx/PolicyMember.ts
> +    pendingAction?: OnyxCommon.PendingAction;
Let's discuss what to do with BaseState [here](https://github.com/blazejkustra/App/pull/1#discussion_r1266822722) @neil-marcellini

2023-07-18 14:13 UTC, blazejkustra commented on src/types/onyx/PolicyMember.ts
> +type PolicyMember = {
Let's discuss what to do with BaseState [here](https://github.com/blazejkustra/App/pull/1#discussion_r1266822722) @neil-marcellini

2023-07-18 16:05 UTC, danieldoglas commented
Credentials.ts LGTM https://github.com/blazejkustra/App/pull/1#pullrequestreview-1527091754

2023-07-18 16:11 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +    iconUrl: string;
I'm not sure where these keys came from, but they are definitely not required

2023-07-18 16:11 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +    isEdited: boolean;
We also have

```
isdeletedParentAction: boolean;
whisperedTo: number[];
reactions: Reaction[];
```

```
type Reaction = {
emoji: string;
users: {
   accountID: number;
   skingTone: number;
}[];
```

2023-07-18 16:11 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
This shape is only valid for `reportActions` with `actionName = IOU`.

2023-07-18 16:11 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +    amount?: number;
Required

2023-07-18 16:11 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +    currency?: string;
Required

2023-07-18 16:11 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +    type?: string;
Required

2023-07-18 16:11 UTC, luacmartins commented on src/types/onyx/Transaction.ts
> +    modifiedCurrency: string;
These are optional

2023-07-19 11:22 UTC, flodnv commented on src/types/onyx/WalletAdditionalDetails.ts
> +type WalletAdditionalDetails = OnyxCommon.BaseState & {
👍

2023-07-19 13:31 UTC, blazejkustra commented on src/types/onyx/PlaidData.ts
> +    plaidAccessToken?: string;
Adjusted, thanks!

2023-07-19 13:31 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +    style: string;
Adjusted, thanks!

2023-07-19 13:32 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +    iconUrl: string;
Thank you, adjusted 👌

2023-07-19 13:34 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +    isEdited: boolean;
Thank you, adjusted 👌

2023-07-19 13:35 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
What if `actionName` is different? What shape does `OriginalMessage` have? @luacmartins

2023-07-19 13:36 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +    amount?: number;
Adjusted

2023-07-19 13:36 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +    type?: string;
Adjusted, thanks!

2023-07-19 13:36 UTC, blazejkustra commented on src/types/onyx/Transaction.ts
> +    modifiedCurrency: string;
Great, thanks!

2023-07-19 13:37 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +    currency?: string;
Adjusted. Thanks!

2023-07-19 16:41 UTC, neil-marcellini commented on src/types/onyx/Paypal.ts
> +    pendingAction?: OnyxCommon.PendingAction;
Coming back to this, my take is that any Onyx key might have these fields so we should have every type intersect with the BaseState. We could do some extensive searching and figure out which keys have these fields and which do not, but I don't think it's worth it. As Vit said, if we never call an API on a key then it won't have `pendingAction`, and probably not `errors` or `isLoading`, but maybe. There might be cases where we set these on the front end only.

Since the fields are optional it makes sense to say that any key type might have them.

2023-07-19 17:14 UTC, madmax330 commented on src/types/onyx/Paypal.ts
> +    username?: string;
Yes

2023-07-20 10:54 UTC, blazejkustra commented on src/types/onyx/Paypal.ts
> +    username?: string;
Thanks!

2023-07-20 13:09 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
Wow, that is very helpful @luacmartins! Thank you, I extracted original message to a separate file - please have a look 👌

2023-07-20 14:23 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
@yuwenmemon @luacmartins 

I think we don't need to type `POLICYCHANGELOG`, it's filtered out [here](https://github.com/blazejkustra/App/blob/809e80b17a3e059c2b0ebc887e5b056c142500c1/src/libs/ReportActionsUtils.js#L357) & it's not really used in the project - [search](https://github.com/search?q=repo%3Ablazejkustra%2FApp%20POLICYCHANGELOG&type=code)

2023-07-20 14:57 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    isOnfidoSetupComplete?: boolean;
These properties are defined in reimbursementAccountDraft prop type [here](https://github.com/blazejkustra/App/blob/302fae9c558cc46b673b94e3daf0f77e7f7bbc4e/src/pages/ReimbursementAccount/ReimbursementAccountDraftPropTypes.js). But maybe it was a mistake? Can somebody confirm if it's correct?

2023-07-20 15:56 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
@blazejkustra those are filtered out in specific scenarios, but we do use those in App [here](https://github.com/Expensify/App/blob/9bd7c716e4dcea1b01ee9827b053e9684e0c1071/src/pages/home/report/ReportActionItem.js#L297), here's an example of `POLICYCHANGELOG.UPDATE_NAME`:

![Screenshot 2023-07-20 at 9 55 31 AM](https://github.com/blazejkustra/App/assets/22219519/bf79df22-7551-4af5-9321-c152923be0b2)

2023-07-20 17:01 UTC, luacmartins commented on src/types/onyx/ReportAction.ts
> +    whisperedToAccountIDs: number[];
This should be optional

2023-07-21 19:44 UTC, neil-marcellini commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    isOnfidoSetupComplete?: boolean;
I've gone through all uses of this key in App, and on the backend, and here are the fields that are written to or accessed. Note that you also have to check for uses of `formID={ONYXKEYS.REIMBURSEMENT_ACCOUNT}`, and then look for any `inputID` in that form which might [set a value into the draft](https://github.com/Expensify/App/blob/85739ea075b554a5a15c8750f2d92bed27005f2f/src/components/Form.js#L315).

I also think it's confusing to have comments stating which page the fields are from so let's remove those.

```ts
type ReimbursementAccountDraft = {
    accountNumber?: string;
    routingNumber?: string;
    acceptTerms?: boolean;
    plaidAccountID?: string;
    plaidMask?: string;
    companyName?: string;
    companyPhone?: string;
    website?: string;
    companyTaxID?: string;
    incorporationType?: string;
    incorporationDate?: string | Date;
    incorporationState?: string;
    hasNoConnectionToCannabis?: boolean;
    isControllingOfficer?: boolean;
    isOnfidoSetupComplete?: boolean;
    ownsMoreThan25Percent?: boolean;
    hasOtherBeneficialOwners?: boolean;
    acceptTermsAndConditions?: boolean;
    certifyTrueInformation?: boolean;
    beneficialOwners?: string[];
    isSavings?: boolean,
    bankName?: string
    plaidAccessToken?: string,
    amount1?: string,
    amount2?: string,
    amount3?: string,
};

export default ReimbursementAccountDraft;
```

2023-07-21 19:44 UTC, neil-marcellini commented on src/types/onyx/ReimbursementAccountDraft.ts
> +    certifyTrueInformation?: boolean;
I checked those [here](https://github.com/blazejkustra/App/pull/1#discussion_r1271025626).

2023-07-21 19:46 UTC, neil-marcellini reviewed
I tried to help out a bit today by reviewing the use of reimbursementAccountDraft.

2023-07-21 22:00 UTC, hayata-suenaga commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
are we talking about `originalMessage` filed of report action for policy/workspace change logs?

Each change log type apparently has its own set of fields...

<img width="300" alt="Screenshot 2023-07-21 at 2 57 39 PM" src="https://github.com/blazejkustra/App/assets/98560306/be721bb0-03e2-4f27-8054-5c3a3dfb47b6">
<img width="300" alt="Screenshot 2023-07-21 at 2 57 49 PM" src="https://github.com/blazejkustra/App/assets/98560306/2494898b-97e3-4d0d-b02a-d89a4af17004">
<img width="300" alt="Screenshot 2023-07-21 at 2 58 08 PM" src="https://github.com/blazejkustra/App/assets/98560306/ef8777aa-34da-4d14-9ddb-3d6d0ac38422">

But do we use `originalMessage` field in NewDot? I think we're using the actual `message` instead of `originalMessage`?

2023-07-21 22:03 UTC, hayata-suenaga commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
Most of the `originalMessage` accesses are for IOU reports. I don't think we use `originalMessage` for policy change logs 🤔 

@yuwenmemon could you double check on this?

2023-07-21 22:08 UTC, hayata-suenaga commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
if this is the case, we can just do `type OriginalMessagePolicyChangeLog = undefined` for now

2023-07-24 09:32 UTC, blazejkustra commented on src/types/onyx/ReportAction.ts
> +type OriginalMessage = {
> if this is the case, we can just do type OriginalMessagePolicyChangeLog = undefined for now inside OriginalMessage.ts

I used `originalMessage: unknown` instead of `undefined`. If we ever need this field we can type it better + I believe unknown is more accurate in this situation, wdyt? @hayata-suenaga

2023-07-25 09:56 UTC, blazejkustra commented
> I assume you already went through all keys and noted whether they use pendingAction, errorFields, errors, isLoading correct?

Yes, that is right @neil-marcellini

2023-07-27 01:33 UTC, hayata-suenaga commented
@blazejkustra 

We're planning to add `react/destructuring-assignment` ESLint rule and, using the `--fix` flag of ESLint, we're planning to change all components to use `react/require-default-props` [here](https://github.com/Expensify/App/issues/22671).

I believe `react/require-default-props` still works even if we de-structure props in JS files as long as there are `PropTypes`, but I don't know about `rulesdir/onyx-props-must-have-default`.

Can you turn off `rulesdir/onyx-props-must-have-default` not only for `ts` and `tsx` files, but for `js` files, too? In other words, can you turn off the rule globally in this PR? 🙇

2023-08-01 11:31 UTC, pecanoro requested changes

2023-08-01 11:31 UTC, pecanoro commented on src/types/onyx/ReimbursementAccount.ts
> +    subStep?: ValueOf<typeof CONST.BANK_ACCOUNT.SUBSTEP>;
Please add a description: `Optional subStep we would like the user to start back on`

2023-08-01 11:31 UTC, pecanoro commented on src/types/onyx/ReimbursementAccount.ts
> +    pendingAction?: boolean;
Are you sure this is a boolean?

![image](https://github.com/blazejkustra/App/assets/6474442/75b64c4f-e3cd-4bf8-96db-6e17bcbcf490)

It looks like it could be one of these:

![image](https://github.com/blazejkustra/App/assets/6474442/2da6d318-082d-4626-9853-d93b4cee88a2)

2023-08-01 12:45 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccount.ts
> +    pendingAction?: boolean;
I missed that, it's not a boolean indeed. Thanks!

2023-08-01 12:47 UTC, blazejkustra commented on src/types/onyx/ReimbursementAccount.ts
> +    subStep?: ValueOf<typeof CONST.BANK_ACCOUNT.SUBSTEP>;
Thanks! Adjusted 👌

2023-08-02 13:09 UTC, blazejkustra commented
I'm closing this PR as I recreated it in Expensify/App: https://github.com/Expensify/App/pull/24054

2023-08-02 13:09 UTC, closed without merging